# Sidebar navigation

- label: 'Top'
  link: '/'
- label: "参考書（完了）"
  items:
    - label: 'ニ種徹底マスター 理論'
      link: '/tetsumasu/riron'
    - label: 'ニ種徹底マスター 電力'
      link: '/tetsumasu/denryoku'
    - label: 'ニ種徹底マスター 機械'
      link: '/tetsumasu/kikai'
    - label: '電験2種 電気数学'
      link: '/math/denkisuugaku'
- label: "参考書（未完了）"
  items:
    - label: 'ニ種徹底マスター 法規'
      link: '/tetsumasu/houki'
- label: "過去問 記録"
  items:
    - label: '1次試験'
      link: '/kakomon/kakomon1'
    - label: '2次試験'
      link: '/kakomon/kakomon2'
- label: 'SNS'
  items:
    - label: 'Twitter'
      link: https://twitter.com/gedo_denki0221
